### ISSUE TITLE
Definir licença do projeto

### ISSUE THREAD

**Issue by lucianopf** [pedromalta/musicsnatch#4]
Acredito que a do MIT seja mais recomendada, o que acha @pedromalta e @romulo1984 ?

**Comment by romulo1984** [comment]
@lucianopf acredito que o MIT, por ser uma faculdade brasileira super renomada, pode sim ser contratada para desenhar a nossa licença.

**Comment by lucianopf** [comment]
@romulo1984 podemos utilizar também a ferramenta [Chose a License](https://choosealicense.com/) pra auxiliar na decisão

**Comment by lucianopf** [comment]
@pedromalta, qual sua opinião sobre isso?

**Comment by pedromalta** [comment]
https://choosealicense.com/no-license/
