### ISSUE TITLE
Gerenciar alterações no escopo do projeto

### ISSUE THREAD

**Issue by lucianopf** [pedromalta/musicsnatch#8]
Gerenciar e atualizar modificações referentes à #7

**Comment by lucianopf** [comment]
Com a adição dos novos colaboradores temos de replanejar o planejamento e portanto isso surtirá efeitos na #7 e #6.

- [ ] Criar documento de alteração de escopo do projeto e do remanejamento dos recursos

**Comment by pedromalta** [comment]
@lucianopf pode fazer a issue #10 por favor...

**Comment by lucianopf** [comment]
Na verdade como minhas atribuições são referentes à full stack software manager, acredito que o melhor indicado para tal tarefa seja o @bazaglia, que é full stack developer senior junior.

Todos concordam com isso @romulo1984 e @metzen?

**Comment by pedromalta** [comment]
@lucianopf por favor faça a issue #10
