### ISSUE TITLE
Redomendação de colaborares

### ISSUE THREAD

**Issue by lucianopf** [pedromalta/musicsnatch#9]
- Full Stack Developer Senior Junior: @bazaglia
- Full Stack Webdesigner Senior: @romulo1984
- Full Stack Software Manager: @lucianopf

**Comment by pedromalta** [comment]
Aprovado!

**Comment by lucianopf** [comment]
Acho válido tbm adicionar o @metzen pra ser o nosso Full Stack Coach Developer!

**Comment by pedromalta** [comment]
Aprovado!!
